name: Continuous Integration
on:
  push:
    branches:
      - "ready/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.KEY}}

      - name: Compile
        run: mvn install

      - name: Merge
        run: git checkout ${GITHUB_REF#refs/heads/}
        run: git rebase origin/master
        run: git branch master
        run: git push origin master:master
        run: git push origin :${GITHUB_REF#refs/heads/}

